all: Install squid-deb-proxy to Vagrant host, try to use Docker host squid-deb-proxy while building Docker images, unified Dockerfiles to better leverage Docker build cache

diff --git a/appliance/postgresql/Dockerfile b/appliance/postgresql/Dockerfile
--- a/appliance/postgresql/Dockerfile
+++ b/appliance/postgresql/Dockerfile
@@ -2,9 +2,12 @@ FROM ubuntu-debootstrap:14.04
 
 ENV DEBIAN_FRONTEND noninteractive
 
-RUN apt-get update &&\
-    apt-get dist-upgrade -y &&\
-    apt-get -qy --fix-missing --force-yes install language-pack-en &&\
+# Try to use the Hosts squid-deb-proxy and fall back if it's unreachable
+RUN (echo 'Acquire { Retries "0"; HTTP { Proxy "http://172.17.42.1:8000"; }; };' > /etc/apt/apt.conf.d/10_docker_hostproxy && apt-get update -qq 2>&1 | grep -q 'Unable to connect to 172.17.42.1:8000' && rm /etc/apt/apt.conf.d/10_docker_hostproxy) || true &&\
+    apt-get update &&\
+    apt-get dist-upgrade -y
+
+RUN apt-get -qy --fix-missing --force-yes install language-pack-en &&\
     update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 &&\
     dpkg-reconfigure locales &&\
     apt-get -y install curl sudo &&\
@@ -21,6 +24,7 @@ RUN apt-get update &&\
       postgresql-9.4-pgrouting &&\
     apt-get clean &&\
     apt-get autoremove -y &&\
+    rm /etc/apt/apt.conf.d/10_docker_hostproxy || true &&\
     echo "\set HISTFILE /dev/null" > /root/.psqlrc
 
 ADD bin/flynn-postgres /bin/flynn-postgres
diff --git a/taffy/Dockerfile b/taffy/Dockerfile
--- a/taffy/Dockerfile
+++ b/taffy/Dockerfile
@@ -1,6 +1,14 @@
 FROM ubuntu-debootstrap:14.04
 
-RUN apt-get update && apt-get -qy install git && apt-get clean
+ENV DEBIAN_FRONTEND noninteractive
+
+# Try to use the Hosts squid-deb-proxy and fall back if it's unreachable
+RUN (echo 'Acquire { Retries "0"; HTTP { Proxy "http://172.17.42.1:8000"; }; };' > /etc/apt/apt.conf.d/10_docker_hostproxy && apt-get update -qq 2>&1 | grep -q 'Unable to connect to 172.17.42.1:8000' && rm /etc/apt/apt.conf.d/10_docker_hostproxy) || true &&\
+    apt-get update &&\
+    apt-get dist-upgrade -y
+
+RUN apt-get apt-get -qy install git && apt-get clean &&\
+    rm /etc/apt/apt.conf.d/10_docker_hostproxy || true
 
 ADD bin/taffy /bin/taffy
 ADD bin/flynn-receiver /bin/flynn-receiver
diff --git a/util/cedarish/Dockerfile b/util/cedarish/Dockerfile
--- a/util/cedarish/Dockerfile
+++ b/util/cedarish/Dockerfile
@@ -1,15 +1,18 @@
 FROM ubuntu-debootstrap:14.04
 
+ENV DEBIAN_FRONTEND noninteractive
+
 # Derived from https://github.com/heroku/stack-images/blob/master/Dockerfile
+
+# Try to use the Hosts squid-deb-proxy and fall back if it's unreachable
+RUN (echo 'Acquire { Retries "0"; HTTP { Proxy "http://172.17.42.1:8000"; }; };' > /etc/apt/apt.conf.d/10_docker_hostproxy && apt-get update -qq 2>&1 | grep -q 'Unable to connect to 172.17.42.1:8000' && rm /etc/apt/apt.conf.d/10_docker_hostproxy) || true &&\
+    apt-get update &&\
+    apt-get dist-upgrade -y
 
 RUN echo 'deb http://archive.ubuntu.com/ubuntu trusty main' >/etc/apt/sources.list &&\
     echo 'deb http://archive.ubuntu.com/ubuntu trusty-security main' >>/etc/apt/sources.list &&\
     echo 'deb http://archive.ubuntu.com/ubuntu trusty-updates main' >>/etc/apt/sources.list &&\
     echo 'deb http://archive.ubuntu.com/ubuntu trusty universe' >>/etc/apt/sources.list &&\
-
-    apt-get update &&\
-    apt-get dist-upgrade -y &&\
-
     apt-get install -y --force-yes \
       autoconf \
       bind9-host \
@@ -56,5 +59,6 @@ RUN echo 'deb http://archive.ubuntu.com/ubuntu trusty main' >/etc/apt/sources.li
       zip \
       zlib1g-dev \
       pigz &&\
+      rm /etc/apt/apt.conf.d/10_docker_hostproxy || true &&\
 
     rm /etc/ssh/ssh_host_*
